workflows:
  build-android:
    name: Build Android APK
    max_build_duration: 60
    environment:
      vars:
        JAVA_HOME: /Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home
    scripts:
      - name: Clean project
        script: ./gradlew clean
      - name: Build Debug APK
        script: ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
